// <auto-generated />
using System;
using JobAgent.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobAgent.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobAgent.Api.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JobAgent.Api.Domain.CandidateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResumePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResumeText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkillsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CandidateProfiles");
                });

            modelBuilder.Entity("JobAgent.Api.Domain.CompanySource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AtsProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoardToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LastJobCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtsProvider", "BoardToken")
                        .IsUnique();

                    b.ToTable("CompanySources");
                });

            modelBuilder.Entity("JobAgent.Api.Domain.DiscoveryRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("CompaniesFailed")
                        .HasColumnType("integer");

                    b.Property<int>("CompaniesScanned")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FunnelJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JobsMatched")
                        .HasColumnType("integer");

                    b.Property<int>("JobsSaved")
                        .HasColumnType("integer");

                    b.Property<int>("JobsSeen")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DiscoveryRuns");
                });

            modelBuilder.Entity("JobAgent.Api.Domain.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AtsProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResumePathUsed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("JobAgent.Api.Domain.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddedByProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplyUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AtsProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("CareersUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExperienceScore")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSaved")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MatchScore")
                        .HasColumnType("integer");

                    b.Property<string>("MatchedSkillsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MissingSkillsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RequiredYears")
                        .HasColumnType("integer");

                    b.Property<int>("SkillScore")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StackScore")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TitleScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplyUrl");

                    b.HasIndex("CandidateProfileId", "CreatedAt");

                    b.ToTable("JobPostings");
                });

            modelBuilder.Entity("JobAgent.Api.Domain.SavedAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresReviewEveryTime")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId", "Key")
                        .IsUnique();

                    b.ToTable("SavedAnswers");
                });

            modelBuilder.Entity("JobAgent.Api.Domain.SearchPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlockedCompaniesCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExcludeFederalJobs")
                        .HasColumnType("boolean");

                    b.Property<string>("ExcludeKeywordsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxAgeHours")
                        .HasColumnType("integer");

                    b.Property<bool>("NeedsSponsorship")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimarySkillsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RemoteOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleKeywordsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScanEveryHours")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique();

                    b.ToTable("SearchPreferences");
                });

            modelBuilder.Entity("JobAgent.Api.Domain.TailoredResume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AtsScoreAfter")
                        .HasColumnType("integer");

                    b.Property<int>("AtsScoreBefore")
                        .HasColumnType("integer");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfirmedSkillsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId", "JobPostingId");

                    b.ToTable("TailoredResumes");
                });
#pragma warning restore 612, 618
        }
    }
}
